---
- name: "Copy CA certificate for Fluent Bit"
  ansible.builtin.copy:
    src: "{{ tls_output_dir }}/ca/ca.crt"
    dest: "{{ fluentbit_host_ca_certificates_directory }}/ca.crt"
    owner: "{{ fluentbit_owner }}"
    group: "{{ fluentbit_group }}"
    mode: "0644"
  become: true

- name: "Copy Fluent Bit certificate"
  ansible.builtin.copy:
    src: "{{ tls_output_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
    dest: "{{ fluentbit_host_ca_certificates_directory }}/fluentbit.crt"
    owner: "{{ fluentbit_owner }}"
    group: "{{ fluentbit_group }}"
    mode: "0644"
  become: true

- name: "Copy Fluent Bit key"
  ansible.builtin.copy:
    src: "{{ tls_output_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.key"
    dest: "{{ fluentbit_host_ca_certificates_directory }}/fluentbit.key"
    owner: "{{ fluentbit_owner }}"
    group: "{{ fluentbit_group }}"
    mode: "0600"
  become: true