---
- name: "Render fluent-bit configuration file from template"
  ansible.builtin.template:
    src: "{{ fluentbit_config_template }}"
    dest: "{{ fluentbit_host_config_directory }}/fluent-bit.conf"
    owner: "{{ fluentbit_owner }}"
    group: "{{ fluentbit_group }}"
    mode: "0644"
  become: true

- name: "Copy Fluent Bit parser file to host"
  ansible.builtin.copy:
    src: "{{ fluentbit_parsers_file }}"
    dest: "{{ fluentbit_host_config_directory }}/parsers.conf"
    owner: "{{ fluentbit_owner }}"
    group: "{{ fluentbit_group }}"
    mode: '0644'
  become: true