---
- name: Prepare for Elasticsearch
  ansible.builtin.import_tasks: prepare.yml

- name: Setup Elasticsearch certificate
  ansible.builtin.import_tasks: setup_certs.yml
  when: elasticsearch_security_enabled
  notify: Restart Elasticsearch

- name: Setup Elasticsearch configuration
  ansible.builtin.import_tasks: setup_config.yml
  notify: Restart Elasticsearch

- name: Pull Elasticsearch image
  ansible.builtin.import_tasks: pull_image.yml

- name: Start Elasticsearch container
  ansible.builtin.import_tasks: start_container.yml

- name: Setup Elasticseatch users & roles
  ansible.builtin.import_tasks: setup_user_role.yml

- name: Setup Elasticseatch ILM policy
  ansible.builtin.import_tasks: setup_ilm_policy.yml
