---
- name: "Copy CA certificate to all nodes"
  ansible.builtin.copy:
    src: "{{ tls_output_dir }}/ca/ca.crt"
    dest: "{{ elasticsearch_host_ca_certificates_directory }}/ca.crt"
    owner: "{{ elasticsearch_owner }}"
    group: "{{ elasticsearch_group }}"
    mode: '0644'
  become: true

- name: "Copy node-specific certificate"
  ansible.builtin.copy:
    src: "{{ tls_output_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
    dest: "{{ elasticsearch_host_ca_certificates_directory }}/elasticsearch.crt"
    owner: "{{ elasticsearch_owner }}"
    group: "{{ elasticsearch_group }}"
    mode: '0644'
  become: true

- name: "Copy node-specific key"
  ansible.builtin.copy:
    src: "{{ tls_output_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.key"
    dest: "{{ elasticsearch_host_ca_certificates_directory }}/elasticsearch.key"
    owner: "{{ elasticsearch_owner }}"
    group: "{{ elasticsearch_group }}"
    mode: '0640'
  become: true
