# Config dirs
node_config_directory: "/etc/elk-ansible"
node_log_directory: "/var/log/elk-ansible"
node_ca_cert_directory: "/usr/share/elk-ansible"
node_custom_config_directory: "/etc/elk-ansible/config"

# Network options
disable_firewall: false

# Docker options
docker_registry: "docker.io"
docker_namespace: "library"
docker_common_tag: "latest"

# Container options
container_name_prefix: "elk_ansible"
container_name_suffix: ""
container_network_mode: "host"
container_default_extra_volumes: []
container_default_healthcheck_retries: 3
container_default_healthcheck_interval: 30
container_default_healthcheck_timeout: 30
container_default_healthcheck_start_period: 5
container_healthcheck_enabled: true

# Elastic options
elastic_version: "8.12.2"
elastic_security_enabled: true

# Security options
enforce_secure_passwords: false
tls_working_dir: "/tmp/elk-ansible"
tls_output_dir: "{{ tls_working_dir }}/es-certificates"
